chat/urls.py
from django.urls import path, include
from . import views
# from .views import LoginView, RegisterForm
urlpatterns = [
    path("", views.home, name="home"),
    path("group_chat/", views.groupChat, name="group_chat"),
    path("notifications/", views.notifications, name="notifications"),
    path("notifications_update/", views.notifications_update, name="notifications_update"),
    path("register_user", views.registrationPage, name="register_user"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutPage, name="logout"),
    path("verification/", views.verification, name='verification'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('join_forum/', views.joinForum, name='join_forum'),
    path('create_forum/', views.createForum, name="create_forum"),
    path('forum/<str:pk>', views.forum, name="forum"),
    path('update_like/<str:post_id>/<str:forum_id>/<str:source>', views.updateLike, name="update_like"),
    path("update_all_users_like/", views.updateAllUsersLikes, name="update_all_users_like"),
    path('update_followers/<str:author_id>/<str:forum_id>/<str:source>', views.updateFollowers, name="update_followers"),
    path('comments/<str:post_id>/', views.comments, name="comments"),
    path('create/', views.create, name="create"),
    path('notification2/<int:num_posts>/', views.notifications_update2, name="notification2"),
    path('notification3/', views.notifications_update3, name="notification3"),
    path('like_unlike/', views.like_unlike_post, name='like_unlike'),
    path("to_be", views.to_be_deleted, name='to_be'),
    path("create_new_message/", views.createNewMessage, name="create_new_message"),
    path("last_message_others/<str:user_id>/", views.displayLastMessageByOthers, name="last_message_others"),
    path("delete_message/<str:pk>/", views.deleteMessage, name="delete_message"),
    path("edit_message/<str:post_id>/", views.editMessage, name="edit_message"),
    path("questions/", views.questions, name='questions'),
    path("answers/<str:question_id>", views.answers, name='answers'),
    path("blog/<slug:person>/<str:item_type>/<int:item_no>", views.blog_answer, name="blog"),
    path("read_unread_notifications/", views.readUnreadNotification, name="read_unread_notifications"),
    path("update_unread_notifications/", views.updateUnreadNotifications, name="update_unread_notifications"),
    path("load_home/", views.loadHome, name="load_home")

    # path('profile/', views.profile, name="profile"),
    # path('create_topic', views.createTopic, name="create_topic"),
    # path('forum_topic', views.forumTopic, name='forum_topic')
    # path("login", LoginView.as_view(), name="login"), I don't really know class views
    # path("register_user", views.RegisterView.as_view(), name="register_user")
]

train/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("chat.urls")),
    path("profile/", include("user_profile.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/forms.py
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms
from django.forms import DateInput
from django.forms import MultiWidget

from .models import (
    Forum,
    Message,
    MessageImage,
    MessageComment,
    Question,
    NFMessage,
    Answer
)
# Topic


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["email", 'username', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Email or Username')


class CreateForumForm(forms.ModelForm):
    class Meta:
        model = Forum
        exclude = ["host", 'participants']


'''class MessageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["body"].widget.attrs.update({
            'placeholder': "What's on your mind",
            'rows': "2",
            'cols': "60",
            'id': "message_box"
        })

    class Meta:
        model = Message
        fields = ["body"]
'''


class MessageWithoutImageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["body"].widget.attrs.update({
            'placeholder': "What's on your mind",
            'rows': "2",
            'cols': "60",
            'id': "message_box"
        })

    class Meta:
        model = Message
        fields = ["body"]


# The complete form
class MessageForm(MessageWithoutImageForm):
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    images.required = False

    class Meta(MessageWithoutImageForm.Meta):
        fields = MessageWithoutImageForm.Meta.fields + ["images", ]

'''
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = '__all__'
'''


class MessageCommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["comment"].widget.attrs.update({id: "df"})

    class Meta:
        model = MessageComment
        fields = ['comment']


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question']


class NFMessageFormWithoutImage(forms.ModelForm):
    class Meta:
        model = NFMessage
        fields = ['message']


class NFMessageForm(NFMessageFormWithoutImage):
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    image.required = False

    class Meta(NFMessageFormWithoutImage.Meta):
        fields = NFMessageFormWithoutImage.Meta.fields + ["image", ]


class AnswerFormWithoutImage(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["answer"]


class AnswerForm(AnswerFormWithoutImage):
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    image.required = False

    class Meta(AnswerFormWithoutImage.Meta):
        fields = AnswerFormWithoutImage.Meta.fields + ["image", ]

chat/views.py
import random

from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Q
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import JsonResponse
from django.core import serializers
from django.http import HttpResponse
# from .ml_codes.tweet2 import SentimentAnalysis
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from .backends import EmailBackend
from user_profile.models import EmploymentCredential

from .models import (
    Member,
    CustomUser,
    Forum,
    Message,
    Leader,
    MessageComment,
    Post,
    MessageImage,
    Question,
    Answer,
    AnswerImage,
    NFMessage,
    NFMessageImage,
    Notification
)
# Like
# Topic
# from django.contrib.auth import authenticate, login, logout
# from django.contrib.auth.forms import UserCreationForm
from .forms import (
    LoginForm,
    RegisterForm,
    MessageForm,
    MessageCommentForm,
    QuestionForm,
    NFMessageForm,
    AnswerForm
)

# TopicForm
# from django.contrib.auth import views as auth_views
# from django.views import generic
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from .forms import CreateForumForm
from django.urls import reverse_lazy


# NB: Forum, Train and Room are all the same concept. That means where one is used, the others are also implied
# And they all mean the same and were used interchangeably.

# global variables (NB: Some of them are not been used. Trace them and delete them.)
current_forum = None  # the current forum in which the user is.
available_posts = None  # all post available in a forum.
no_of_likes = ""  # Total number of likes a person has.
like_status = False  # To know whether or not person likes the status of another
unread_notifications = 0  # notifications not yet read


# posts = None


def home(request):
    """
    The home page of the train app.
    :param request: a html request.
    :return: returns the home.html page and the accompanying data in a context
    """
    forums = Forum.objects.all()
    result = " "
    form = NFMessageForm()
    emc = EmploymentCredential.objects.all()
    global unread_notifications

    if request.method == 'POST':
        form = NFMessageForm(request.POST or None, request.FILES or None)
        files = request.FILES.getlist('images')
        print('message =', files)

        if form.is_valid():
            # creating the message and saving the images
            message = NFMessage.objects.create(author=request.user, message=request.POST.get('message'))

            for file in files:
                NFMessageImage.objects.create(message=message, image=file)

            # creating notification for  posts
            new_post_notice = Notification.objects.create(notifier=request.user,
                                                          item_no=message.id, item_type="post", notice=message.message)
            users = CustomUser.objects.all()
            for user in users:
                new_post_notice.notifyee.add(user)

            # print("message", message)
            print("message_type",  request.POST.get('message'))
            if request.POST.get('message') != "":
                unread_notifications = unread_notifications + 1
                # d = 2
                print(request)

            return redirect("home")

        else:
            return redirect("create_forum")

    comment_form = MessageCommentForm()
    comments = MessageComment.objects.all()
    notifications = Notification.objects.all()

    ''' if request.method == "POST":
        text = request.POST["text"]'''
    '''sentiment = SentimentAnalysis()
    result = sentiment.predictor([text])
    redirect("sentiment")'''

    posts = NFMessage.objects.all()
    posts = random.sample(list(posts),5) if posts.count() >= 5 else random.sample(list(posts), posts.count())
    images = NFMessageImage.objects.all()
    users = CustomUser.objects.all()

    context = {
        # 'result': result,
        'forums': forums,
        'login': False,
        'posts': posts,
        'comment_form': comment_form,
        'comments': comments,
        'images': images,
        'emc': emc,
        'users': users,
        # 'd': d,
        # 'unread_notifications': unread_notifications,
        #'notifications': notifications
        # 'question': question,

    }
    return render(request, 'base/home.html', context)


'''def sentimentResult(request):
    return render(request, 'base/home.html', {})'''


def loadHome(request):
    """
    reloads home
    :param request:
    :return: returns the load_home.html page
    """
    context = {}
    return render(request, 'base/load_home.html', context)


def groupChat(request):
    context = {}
    return render(request, 'base/group_chat.html', context)


def notifications(request):
    """
    A page that displays notifications to a user.
    :param request:
    :return: returns notifications.html and the accompanying data.
    """
    users = CustomUser.objects.all()
    forums = Forum.objects.all()

    notifications = Notification.objects.all()

    # lead = Leader.objects.get(leader_id=1)
    # follows = lead.followers.all()
    # print(follows)

    # getting all the leaders
    leaders = Leader.objects.all()
    following_leaders = [] # the id of the leaders a user is following
    for i in range(1, len(leaders)+1):
        list_ = []
        try:
            leader = Leader.objects.get(leader_id=i)
            list_ = leader.followers.all()
            print(list_)
        except:
            pass
        else:
            leader = Leader.objects.get(leader_id=i)
            list_ = leader.followers.all()
            print(list_)

        if request.user in list_:
            following_leaders.append(i)

    for i in range(0, len(following_leaders)):
        # Notification.objects.get(notifier_id=1)
        pass

    notifications = Notification.objects.filter(notifier_id__in = following_leaders)
    print(following_leaders)
    # print(lead)

    answers = Answer.objects.all()
    nf_messages = NFMessage.objects.all()
    questions = Question.objects.all()

    context = {'forums': forums,
               'notifications': notifications,
               'answers': answers,
               'nf_messages': nf_messages,
               'questions': questions,
               'users': users,
               }
    return render(request, 'base/notifications.html', context)


def readUnreadNotification(request):
    """
    gives the state of the number of unread messages
    :param request:
    :return: a JsonResponse of the number of unread notifications
    """
    global unread_notifications
    # display_parameter = 0
    print("unread_notifications = ", unread_notifications)
    return JsonResponse({'unread_notifications': unread_notifications})
    # 'display_parameter': display_parameter})


def updateUnreadNotifications(request):
    """
    updates the number of unread notifications
    :param request:
    :return: gives a Json response of the number of unread notifications
    """
    global unread_notifications
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == "XMLHttpRequest"
    if is_ajax:
        print(request.GET)
        unread_notifications = int(request.GET["unread_notifications"])
    print('unread =', unread_notifications)
    return JsonResponse({'unread_notifications': unread_notifications})


# START
# these are for tutorial purposes
# The notifications 1, 2 and 3 show three different ways of using JSONreponse
def notifications_update3(request):
    text = "I am a text"
    return JsonResponse({"text": text})

def notifications_update2(request, num_posts):
    visible = 3
    upper = num_posts  # upper, the number of posts to display in total, is 3 initially
    # but increases with each button click
    lower = upper - visible
    print('lower = %s, upper = %s , visible = %s' % (lower, upper, visible))

    messages = Post.objects.all()
    size = messages.count()
    print('number of messages', size)
    context = {}

    message = []
    for message_ in messages:
        item = {
            'id': message_.id,
            'message': message_.message,
            'title': message_.title,
            'liked': True if request.user in message_.liker.all() else False,
            'like_count': message_.like_count,
        }
        message.append(item)

    print(message)
    return JsonResponse({'messages': message[lower:upper], 'size': size})


def notifications_update(request):
    forums = Forum.objects.all()
    context = {}

    return JsonResponse({
        "forums": list(forums.values())
    })

    # return render(request, 'base/notifications.html', context)
# END


def like_unlike_post(request):
    """
    likes or unlikes a post.
    :param request:
    :return: a boolean in Json format, where true is like and false is unlike
    """
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == "XMLHttpRequest"
    if is_ajax:
        pk = request.POST.get('pk')
        obj = Post.objects.get(pk=pk)
        if request.user in obj.liker.all():
            liked = False
            obj.liker.remove(request.user)
        else:
            liked = True
            obj.liker.add(request.user)

        return JsonResponse({'liked': liked, 'count': obj.like_count})


like = True


# to be removed
def to_be_deleted(request):
    # Here I show how to make a like button
    '''global like
    if request.method == "POST":
        if request.POST.get('like_id'):
            like = False
        else:
            like = True

chat/templates/base/acc_active_email.html
{% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

chat/templates/base/answers.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
    <link type="text/css" rel="stylesheet" href="{% static 'style/answer.css' %}">
{% endblock %}
{% block body %}
    <div class="answers_container">
    {% for question in questions %}

        <div class="answer_div">
            <img id="closer"  style="float: right;" src="/static/images/close.png" height="12px" width="12px" >
            <p>{{question}}</p>
            {% for question_id, number in answers.items %}
                {% if question_id == question.id %}
                    {{number}}
                {% endif %}
            {% endfor %}
            <span id={{question.id}} class="answers">Answer</span>
            <span>Follow</span>
            <span>Pass</span>
            <img style="float: right" src="{% static 'images/menu(1).png' %}" height="22px" width="22px">
        </div>
    {% endfor %}
    </div>
    <script type="module" src="{% static 'javascript/answers.js' %}"> </script>
{% endblock %}

chat/templates/base/concept_tester.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <style>
        #id_images {
            display: none;
            poin
        }
    </style>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <p>{{field.label}}</p>
        <p>{{field}}</p>
    {% endfor %}
    <label for="id_images">
     <img src="/static/images/view.png" height="20px" weight="20px;">
    </label><br>
    <input type="submit">
</form>

<div>
    {% for message in messages %}
        <div style="border:1px solid black; background:lightblue;">
            <p>{{message.body}}</p>
            {% for image in images %}
                {% if image.message_id == message.id %}
                <img src="{{image.image.url}}" height="30px" width="40px">
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
</div>

</body>
</html>

-->


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>

<form id="form">
	<input id="files" type="file" accept="images/*" multiple>
	<input  id="result" type="button" value="result">
</form>

<script>
	files = document.getElementById("files")
	file_name = files.value.substring(12,files.value.length)


	file_list = []

	files.onclick = function(){
		create_file = new File(["image"], file_name, {type: "image"})
		file_list.push(create_file)
	}

	result = document.getElementById("result")
	new_files_.pust(files.files[0])
	result.onclick= function(){
		alert(file_list)
		for(i=0; i<=file_list.length; i++){
			url =URL.createObjectURL(file_list[i])
			image = document.createElement("img")
			image.setAttribute("src",`${url}`)
			image.setAttribute("height","70%")
			image.setAttribute("width","350px")
			document.body.append(image)
		}

	}

	/* result.onclick= function(){
			alert(file_list)
		for(i=0; i<=files.files.length-1; i++){
				url =URL.createObjectURL(files.files[i])
				image = document.createElement("img")
				image.setAttribute("src",`${url}`)
				image.setAttribute("height","70%")
				image.setAttribute("width","350px")
				document.body.append(image)


		}
	} */
</script>

</body>
</html>

chat/templates/base/forum_topic.html
{% extends 'base.html' %}
{% block body %}
<p> {{forum}} Forum </p>
<p> Topic: {{topic}}</p>
{% endblock %}

chat/templates/base/home.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
    {% if user.is_authenticated %}
        <link type="text/css" rel="stylesheet" href="{% static 'style/home_after_login.css' %}">
    {% else %}
         <link type="text/css" rel="stylesheet" href="{% static 'style/home.css' %}">
    {% endif %}
{% endblock %}

{% block body %}
{% if user.is_authenticated %}
<style>
    @font-face{
        font-family: open_sans;
        src: url("{% static 'fonts/Open_Sans/static/OpenSans/OpenSans-Regular.ttf' %}") format('truetype');
    }

    @font-face{
        font-family: open_sans;
        font-weight: bold;
        src: url("{% static 'fonts/Open_Sans/static/OpenSans/OpenSans-Bold.ttf' %}") format('truetype');
    }

    @font-face{
        font-family: open_sans_light;
        src: url("{% static 'fonts/Noto_Sans/NotoSans-Light.ttf' %}") format('truetype');
    }

    .post p {
        font-family: open_sans;
        font-size: 16px;
    }

    .post #post_author {
       font-family: open_sans;
       font-weight: bold;
       font-size: 14px;
    }

    .post #credentials_ {
       font-family: open_sans_light;
       font-size: 14px;
       color: rgb(30,30,30);
    }
</style>
<div class="nav_and_section" >
    <div class="nav_nav">
        <div><a href="{% url 'create_forum' %}"><span style="margin-right:30px; display:inline-block; background: rgb(190,190,190); padding:5px 20px 5px 20px;">+</span>Create Train</a></div>
        {% for forum in forums %}
            <div>
                <a href="{% url 'forum' forum.id %}">{{forum}}</a>
            </div>
        {% endfor %}
    </div>

    <div class="section">
        <div class="pre_section">
            {% comment %}
                <h3> Welcome {{user.name}} </h3>
                <h4> This App does a Sentiment Analysis on a Piece of Imputed Text</h4>
            {% endcomment %}

            <div class="pre_section_search" >
                    {% if user.avatar.url != '/images/view.png' %}
                       <div style="position: absolute; display: inline-block;">
                           <img style="display: inline-block; margin-top: 45px; border-radius:
                           50%; margin-left:1px; margin-top: 1px; " src="{{user.avatar.url}}"
                                height="40px" width="40px" >
                       </div>
                    {% else %}
                        <div id="profile_circle" class="profile_circle" user_initial={{user.username}}
                             style="margin-right: -40px; margin-top: 5px; ">
                            <div id="user_initial"  class="home_profile_div_first" style="font-family: open_sans;">
                                {{user.username}}
                            </div>
                        </div>
                    {% endif %}

                <div style="display: inline-block; margin-left: 50px; margin-top: 10px; position: absolute; width:55%">
                    <input type="search" placeholder="What do you want to share?" disabled>
                </div>
            </div>
            <div id="pre_section_2" >
                   <span id="questions">
                       <a>
                           <img src="{% static 'images/question-1.png' %}" height="17px" width="17px">
                           Ask
                       </a>
                   </span>

                   <span>
                       <a href="{% url 'answer_question' %}">
                           <img src="{% static 'images/answer.png' %}" height="17px" width="17px">Answer
                       </a>
                   </span>
                   <span id="non-forum-post">
                       <img src="{% static 'images/edit.png' %}" height="17px" width="17px">Post
                   </span>
            </div>

        </div>
        {# A Selection of  the first 5 messages from each forum. Would later be a Random selection. #}
        {% for post in posts %}
           {# {% if user != post.author %} #}
                <div class="post" >
                    {% for user_ in users %}
                        {% if user_ == post.author %}
                            {% if user_.avatar.url != '/images/view.png' %}
                                <img src="{{user_.avatar.url}}" style="border-radius: 50%; position: absolute; " width="35px" height="35px">
                            {% else %}
                                <div class="profile_circle" style="margin-left: -0.05px; margin-right: -40px;">
                                    <div class="home_profile_div" >{{user_}}</div>
                                </div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}

                    <span id="post_author"  style="margin-left: 50px;">{{post.author}}</span>

                    {# follow button #}
                    <form {# action="{% url 'update_followers' post.author_id  post.forum_id 1 %}" #} method="POST">
                        {% csrf_token %}
                        <button  id="follow" type="submit" name="author_id" value="{{post.author_id}}" class="btnprimary">
                               follow
                        </button>
                    </form>

                    {% for emc in emc %}
                        {% if emc.user_em.id == post.author_id %}
                        <br>
                        <span id="credentials_" style="margin-left: 50px;">{{emc.position}} at {{emc.company_organization}} ({{emc.start_year|date:'Y'}} - {{emc.end_year|date:'Y'}})</span>
                        {% endif %}
                    {% endfor %}

                    <small id="time_posted"> . {{post.created|timesince}}</small>

                    <p>{{post.message}}</p>

                    {# image #}
                    <div style="text-align: center; margin:0; padding:0;">
                        {% for image in images %}
                        {% if image.message_id == post.id %}
                            <img src={{image.image.url}} height="70%" width="300px">
                        {% endif %}
                    {% endfor %}
                    </div>

                    {# like button #}
                    <form  {# action="{% url 'update_like' post.id post.forum_id 1 %}" #} method="POST">
                        {% csrf_token %}
                        <button type="submit" name="post_id" value="{{post.id}}" class="btnprimary">
                               <img src="{% static 'images/like.png' %}" height="20px" width="20px" >
                        </button>
                        <small>  {{post.likes_total}} </small>
                    </form>

                    {# comment button:  the button that opens the comment box and comments #}
                    <button id={{post.id}} onclick="showHideForm('{{post.id}}', '{{post.id}}a', 'Comment')"> <img src="{% static 'images/speech-bubble.png' %}" height="20px" width="20px" > </button>

                    <div id={{post.id}}a style="display:none">
                        <form   action="{% url 'comments' post.author_id   %}" method="POST">
                            {% csrf_token %}
                            {{comment_form}}
                            <small> <input type="submit"></small>
                        </form>
                        {# comments #}
                        {% for comment in comments %}
                            {% if comment.message_id == post.id %}
                                <div style="background:yellow; margin-left:20px;" >
                                    <p><small>{{comment.commenter}}</small></p>
                                    <p>{{comment.comment}}</p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>


                </div>
           {# {% endif %} #}
        {% endfor %}
    </div>


</div>
<script src="{% static 'javascript/home_after_login.js' %}"> </script>
{% else %}
  <div id="new_bees">
      <h1>D-Chatters</h1>
      <h4>A place to Discuss a variety of topics and get better understanding</h4>
      <p id="policy">By continuing, you indicate that you agree to Chatter's Term of Service and Privacy Policy</p>

      <div id="sign_up_login">
          <p id="login_p"><a href="{% url 'login' %}">Login</a></p>
          <p id="sign_up_p"><a href="{% url 'register_user' %}">Sign up with email</a></p>
      </div>

      <div id="others">
          <div><p>About</p></div>
          <div><p>Carriers</p></div>
          <div><p>Languages</p></div>
          <div><p>@ OPaul Studio, Inc. 2022</p></div>
      </div>


  </div>

</div>
    {% endif %}
{% endblock %}




<!-- <form  method="POST">
        {% csrf_token %}
        <label> Enter Text</label><br>
        <input type="text" name="text"><br>
        <input type="submit">
    </form>

    {% for member in members %}
        <p>{{member.name}} </p>
    {% endfor %}


    {% if result.isspace == False %}
        <p> This text is {{result}} </p>
    {% endif %}
-->

chat/templates/base/join_forum.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
    <link type="text/css" rel="stylesheet" href="{% static 'style/forum/join_forum.css' %}">
{% endblock %}

{% block body %}
<div class="container">
    <div></div>

    <div class="info">
        {% for forum in forums %}
        <div class="forum_">
            <a href="{% url 'forum' forum.id %}">{{forum.name}}
                <div class="description">{{forum.description}}</div>
            </a>
        </div>
        {% endfor %}
    </div>

    <div></div>
</div>
{% endblock %}

chat/templates/base/load_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <div id="temp_header">

        </div>
        <div id="temp_header_sub"></div>
        <div id="d_train"> D-T</div>
        <div id='loading_bar_1'></div>
        <div id='loading_bar_2'></div>
        <div id='loading_bar_3'></div>
    <script src="{% static 'javascript/load_home.js' %}"></script>
</body>
</html>

chat/templates/base/questions.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
    <link type="text/css" rel="stylesheet" href="{% static 'style/answer.css' %}">
{% endblock %}
{% block body %}
    <div class="answers_container">
    {% for question in questions %}
        <div class="answer_div">
            <img id="closer"  style="float: right;" src="/static/images/close.png" height="12px" width="12px" >
            <p>{{question}}</p>

            {% for answer in answers %}
                {% if answer.question_id == question.id %}
                    <p >{{answer.question_id|length}}</p>
                {% endif %}
            {% endfor %}

            <span id={{question.id}} class="answers">Answer</span>
            <span>Follow</span>
            <span>Pass</span>
            <img style="float: right" src="{% static 'images/menu(1).png' %}" height="22px" width="22px">
        </div>
    {% endfor %}
    </div>
    <script type="module" src="{% static 'javascript/answers.js' %}"> </script>
{% endblock %}

chat/templates/base/reg_status.html
{% if registration == "succeeded" %}
  <h3>Your email address has been verified.</h3>
  <p>You can now <a href="{% url 'login' %}" >login</a></p>
{% elif registration == 'failed' %}
  <h3>Your email address has not been verified.</h3>
  <p>You can now <a href="" >An error occurred</a></p>
{% endif %}